### ISSUE TITLE
Installation  vs Makefile

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab-demo#2]
Per suggestion from @fperez , I tried installing the fork from @jasongrout but `make demo` doesn't handle the environment setup from `INSTALL.txt` Should there be changes to the makefile or readme to take care of environment setup for the demo?

**Comment by jzf2101** [comment]
In #9, I'm keeping these as separate files, but I'm wondering if we should explicitly tell people to call both scripts or to run `INSTALLATION.txt` in the make file?

**Comment by blink1073** [comment]
I'd say running it as `bash INSTALL.txt` should be good.

**Comment by jzf2101** [comment]
Ok I'll create an issue to add environment instructions
