### ISSUE TITLE
`movethis` `movethishere`?

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab-demo#25]
@ian-r-rose @ellisonbg We've been using dummy files and folder `movethis` and `movethishere` to show drag and drop.  Do we want to keep these in the repo? They're currently not in master or the `invoke` script?

**Comment by sccolbert** [comment]
They were created by the old makefile:
https://github.com/jupyterlab/jupyterlab-demo/blob/2d02b9698725e88e229dd781866dd99db406934c/Makefile#L28-L32

**Comment by jzf2101** [comment]
Will put it back
