### ISSUE TITLE
`INSTALL.txt` errors

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab-demo#3]
@jasongrout

`Invalid requirement: 'bqplot=0.9.0b10'
= is not a valid operator. Did you mean == ?`

`- Writing config: /Users/4d/anaconda/envs/jlabdemo/etc/jupyter/labconfig
        X is not version compatible with installed JupyterLab version 0.16.2
            Expects JupyterLab version ^0.13.1 from packaged module jupyterlab_geojson@0.2.1/lib/widget.js
            Expects JupyterLab version ^0.13.1 from packaged module jupyterlab_geojson@0.2.1/lib/plugin.js`

`Collecting dask-labextensions
  Could not find a version that satisfies the requirement dask-labextensions (from versions: )
No matching distribution found for dask-labextensions`

**Comment by jzf2101** [comment]
jupyterlab_geojson 0.4.0 does not work with jupyterlab 0.16.2 but later versions are not available

https://github.com/jupyterlab/jupyterlab_geojson/issues/38

**Comment by jzf2101** [comment]
At the same time `jupyterlab_widgets` requires jupyterlab 0.16.2

```jupyterlab_widgets
- Writing config: /Users/4d/anaconda/envs/jlabdemo/etc/jupyter
        X is not version compatible with installed JupyterLab version 0.13.1
            Expects JupyterLab version ^0.16.2 from packaged module @jupyterlab/nbwidgets@0.6.15/lib/plugin.js```

**Comment by jzf2101** [comment]
Additional error messages after trying to patch more:

```
Symlinking: /Users/4d/anaconda/envs/demo/share/jupyter/labextensions/jupyter-threejs -> /Users/4d/anaconda/envs/demo/lib/python3.6/site-packages/pythreejs/staticlab

    - Validating...

     OK has necessary files?

      X has jupyter-threejs entry point?
```


```
[InstallLabExtensionApp] CRITICAL | Bad config encountered during initialization:


[InstallLabExtensionApp] CRITICAL | Unrecognized flag: '--py'
```

**Comment by jzf2101** [comment]
Have to install jupyterlab 0.7.0 to get to the error msgs above

**Comment by Carreau** [comment]
Feel free to ping me if ou need anything. I'm more on the IPython/kernel side, but can try to help. I can likely also give you permission on repositories or various services.

**Comment by blink1073** [comment]
The following will get JupyterLab@0.23 and ipywidgets working.  The other renderers have not yet been updated for the new extension system:

```
pip install jupyterlab==0.23
pip install ipywidgets==7.0.0a4
jupyter labextension install @jupyterlab/nbwidgets@0.20.2
```

**Comment by jzf2101** [comment]
@blink1073 Thanks I'll update the install accordingly

**Comment by jzf2101** [comment]
@blink1073 I think they're still not working so I took out many of the extensions except googledocs

**Comment by jzf2101** [comment]
@jasongrout @blink1073  @ellisonbg geojson and json now work with 0.25.1 but now bqplot and ipywidgets don't work with 0.25.1. @jasongrout can we get widgets and bqplot to work with 0.25.1

Additionally jupyterlab-manager doesn't work with 0.25.1

**Comment by jzf2101** [comment]
@jasongrout you redid the `invoke environment` to set up 0.25.2 with bqplot, widgets, geojson, and json correct? Could you PR?
