### ISSUE TITLE
Geojson of lightning strikes

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab-demo#30]
We could include a geojson file of lightning strikes, and maybe a large csv of them, you know, for lightning talks :). It'd be fun to give a talk where the data was all puns on lightning talks.

**Comment by jzf2101** [comment]
Found something from Japan:

https://github.com/9SQ/jma-liden2geojson

**Comment by ian-r-rose** [comment]
There is a NOAA lightning database [here](https://www.ncdc.noaa.gov/swdi/#TileSearch), which can export to GeoJSON. The explorer seems pretty limited, but perhaps there is a bulk download somewhere.

**Comment by jasongrout** [comment]
Cool, thanks! Needless to say, this is a very low priority. Next time I give a lightning talk, I'll probably put some cycles towards it, though.

**Comment by jzf2101** [comment]
@ian-r-rose are you referring to Lightning strikes from Visala?  They just do a daily aggregate count as far as I know for a given lat long. indices of where the strikes occurred I can't find.

**Comment by ian-r-rose** [comment]
Yes, that is what I was referring to. I didn't look too carefully :smile:
