### ISSUE TITLE
Missing some datafiles

### ISSUE THREAD

**Issue by willingc** [jupyterlab/jupyterlab-demo#33]
I tried to get the demos working for a presentation this morning. Even after using invoke to install the data files, the files could not be found. Are some of the datafiles missing? Or is it a path issue on my part?

**Comment by blink1073** [comment]
Hi hi, I just tried from a clean install and the only file I saw missing was an `all.fasta` file.  Do you know specifically what else was missing?

**Comment by willingc** [comment]
Thanks @blink1073. Yes, I was trying the fasta file. I just retried everything else and it looks fine to me.

**Comment by willingc** [comment]
BTW the examples are fabulous 👍

**Comment by jzf2101** [comment]
@jasongrout any thoughts on how we can include this?

**Comment by Zsailer** [comment]
@jzf2101 , @jasongrout 

I think an aligned fasta file containing a popular virus, like Zika or Ebola, would be perfect example for the fasta renderer demonstration. Most people have heard of those viruses and there are published, curated fasta files in the literature. 

If y'all like that idea, I can compile this for you and submit as a PR.
