### ISSUE TITLE
Test Invoke Scripts on Windows?

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab-demo#35]
Based on the documentation I've read so far from invoke, it's unclear to me if the shell commands in the invoke script will run on Windows.  Could someone confirm?

**Comment by blink1073** [comment]
I tried quickly in a Windows VM.  At first I got the error:

```
You indicated pty=True, but your platform doesn't support the 'pty' module!
creating environment jupyterlab-demo
```

I set `pty=False` but there are other things that need to be updated:

```python
FileNotFoundError: [WinError 3] The system cannot find the path specified
creating environment jupyterlab-demo
```

I think its fair to state in the readme that the demo does not yet support Windows.
