### ISSUE TITLE
#31 change copyright date.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab-demo#47]
#31 change Copyright date from 2016 to 2017. IIRC the copyright date should be the date of _first_ copyright and is implicitly YYYY-Present. Should it be changed back ? @ellisonbg ?

**Comment by jzf2101** [comment]
@Carreau given the discussion in https://github.com/jupyter/governance/issues/37 do we still want to keep this open?

**Comment by fcollonval** [comment]
Closing as the date in License is 2017
