### ISSUE TITLE
Failed to create the environment - Can't find any collection named 'tasks'!

### ISSUE THREAD

**Issue by bityob** [jupyterlab/jupyterlab-demo#64]
Using:
- Windows 10
- Miniconda
- Anaconda Prompt to run conda

```batch
(base) C:\>conda --version
conda 4.4.10
```

Installation was ended successfully 

```batch
(base) C:\>conda install -c conda-forge invoke pyyaml
Solving environment: done

# All requested packages already installed.
```

But creating the environment failed -

```batch
(base) C:\>invoke environment
Can't find any collection named 'tasks'!
 ```

Thanks.

**Comment by ruben-aghayan** [comment]
Hi bityob,
Are you in the same folder as the repo? That's where the tasks.py file is for the invoke command.

**Comment by jzf2101** [comment]
I agree, I think that's what's going on.  You have to be in the base directory of the repo.

**Comment by bityob** [comment]
@ruben-aghayan  @jzf2101 

Thanks, this was the problem.

Didn't now how to use correctly the `invoke` command,

maybe it will help to mention it in the readme file before this command.

**Comment by jzf2101** [comment]
Will add that note thanks
