### ISSUE TITLE
Determine Origin of Example Content in Demo

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab-demo#7]
@jasongrout @fperez : @ellisonbg suggested we think about ideas for content and pin down the provenance of our content in the demo.  I've started by creating a dropbox paper document that lists where everything comes from.  Please fill in relevant information if I've determined you've made the first commit

**Comment by jzf2101** [comment]
@jasongrout @ellisonbg When we use outside content from the makefile, we should know what we actually end up using.  Can you two help provide clarification on what ends up usually being covered? Ideally, we should consolidate the additional content to figure out what we specifically use and give attribution.

**Comment by jzf2101** [comment]
@ian-r-rose @ellisonbg @sccolbert @jasongrout It appears most often we use a large csv file, an example notebook, a geojson, an image, a vegalite file

**Comment by sccolbert** [comment]
We also use markdown files and text editors to show live update/editing of markdown files. There's also the realtime collaboration stuff that Ian built.

**Comment by sccolbert** [comment]
Here's the most recent talk we did:
https://channel9.msdn.com/events/PyData/Seattle2017/BRK11

**Comment by jzf2101** [comment]
the markdown and the text editor content are original, so we don't need to worry about keeping it.  I'm wondering if we should speed up the installation by picking a few files to use as examples for each type of file.

**Comment by sccolbert** [comment]
It helps to have a markdown file with pre-defined content in it, so that we
aren't writing from scratch, but modifying something with some existing
content.

**Comment by jzf2101** [comment]
Will add license table to repo

**Comment by jzf2101** [comment]
closed by #34
