### ISSUE TITLE
solving environment failed

### ISSUE THREAD

**Issue by axiezai** [jupyterlab/jupyterlab-demo#78]
Tried 'invoke environment' inside the repo directory using:
miniconda 4.5.11
python 3.6.5

invoke environment fails with the following messages:
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - scikit-learn=0.18
  - xtensor-blas=0.12
Use "conda info <package>" to see the dependencies for each package.

Any help is appreciated!

**Comment by blink1073** [comment]
Hi @axiezai, what is the output of `conda info`?

**Comment by axiezai** [comment]
Conda info: 

active environment : None
       user config file : /home/axiezai/.condarc
 populated config files : /home/axiezai/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /home/axiezai/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/axiezai/miniconda3/pkgs
                          /home/axiezai/.conda/pkgs
       envs directories : /home/axiezai/miniconda3/envs
                          /home/axiezai/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Linux/4.4.0-134-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by blink1073** [comment]
Can you please try removing the version spec on those packages in binder/environment.yml and see where you end up for each version (e.g. conda list  xtensor)?

**Comment by axiezai** [comment]
The environment was built successfully with no version specs, here are the versions in the environment:
xtensor                   0.17.3                        0    QuantStack
xtensor-blas              0.13.1          blas_openblas_0  [blas_openblas]  QuantStack
scikit-learn              0.19.2          py36_blas_openblasha84fab4_201  [blas_openblas]  conda-forge

I was able to open and run the lorenz notebook without a problem, I'm not sure exactly which notebook makes use of xtensor and scikit-learn, if you need me to test them out, please let me know. 

And if you think these versions are adequate, I assume we can close this issue?

**Comment by blink1073** [comment]
Does it work for you locally if you change the version specs to 0.13 and 0.19?  If so, would you mind making a PR?

**Comment by axiezai** [comment]
I will give this a shot tomorrow after my traveling ends, will keep you updated. And yes, will make a PR if everything works!

**Comment by blink1073** [comment]
Great, thanks!

**Comment by axiezai** [comment]
Changing the version specs to 0.13 and 0.19 respectively worked. 

I created a PR. Let me know if everything looks good, I will leave closing the issue to you :) thank you for the help.

**Comment by blink1073** [comment]
Cheers, and congratulations on your first contribution to JuptyerLab :tada:!
