### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by shreddd** [jupyterlab/jupyterlab-demo#85]
Looks like the last build has not been passing in Travis with:
```
AttributeError: module 'tornado.web' has no attribute 'asynchronous' 
```

Possibly related to: 
https://github.com/conda-forge/nbconvert-feedstock/issues/27

Note that that currently this repo does not work on binder (running notebook simply hangs)

**Comment by ian-r-rose** [comment]
Thanks @shreddd! This should be fixed by #83.
