### ISSUE TITLE
Plotly missing as dependency

### ISSUE THREAD

**Issue by nathanrpage97** [jupyterlab/jupyterlab-demo#94]
Hi, jupyterlab-plotly extension is installed, but plotly itself is missing.

**Comment by blink1073** [comment]
Good catch, @nathanrpage97!  Do you want to submit a PR to remove [this line](https://github.com/jupyterlab/jupyterlab-demo/blob/268524d006da026ad1a71b37e4e83c1d0f8d0128/tasks.py#L53)?

**Comment by nathanrpage97** [comment]
Are we fine with adding plotly to the list?

**Comment by blink1073** [comment]
I'm hesitant to add one that isn't maintained by Jupyter developers to the core demo
